import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131315",
        "primary": "#bec6e0",
        "inverse-primary": "#565e74",
        "tertiary-fixed-dim": "#dec29a",
        "surface-container-highest": "#353436",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#303032",
        "on-secondary": "#002e6a",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary": "#dec29a",
        "surface-container": "#1f1f21",
        "on-tertiary-fixed-variant": "#574425",
        "on-tertiary-fixed": "#271901",
        "error": "#ffb4ab",
        "on-background": "#e4e2e4",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1b1b1d",
        "surface-dim": "#131315",
        "surface-container-high": "#2a2a2b",
        "on-surface-variant": "#c6c6cd",
        "outline-variant": "#45464d",
        "on-secondary-fixed-variant": "#004395",
        "error-container": "#93000a",
        "on-primary-fixed": "#131b2e",
        "secondary-container": "#0566d9",
        "on-error": "#690005",
        "secondary": "#adc6ff",
        "on-tertiary-container": "#957d5a",
        "on-tertiary": "#3e2d11",
        "on-primary-container": "#798098",
        "on-primary": "#283044",
        "on-secondary-fixed": "#001a42",
        "outline": "#909097",
        "secondary-fixed": "#d8e2ff",
        "tertiary-container": "#231500",
        "surface-variant": "#353436",
        "primary-fixed-dim": "#bec6e0",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#e6ecff",
        "surface-tint": "#bec6e0",
        "background": "#131315",
        "surface-bright": "#39393b",
        "on-surface": "#e4e2e4",
        "secondary-fixed-dim": "#adc6ff",
        "primary-container": "#0f172a",
        "inverse-surface": "#e4e2e4",
        "tertiary-fixed": "#fcdeb5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin": "32px",
        "stack-lg": "24px",
        "unit": "4px",
        "gutter": "24px",
      },
      fontFamily: {
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-poppins)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-xs": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-poppins)", "sans-serif"],
        "metric-xl": ["var(--font-poppins)", "sans-serif"],
        "headline-md": ["var(--font-poppins)", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-xs": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "metric-xl": ["36px", { lineHeight: "1", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
